name: "godot-ci export"
on: 
  push:
    tags: 
      - "test*"
  
env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: wasteland-test-build
  PROJECT_PATH: project
  
jobs:


  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.1 # https://github.com/abarichello/godot-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # https://github.com/actions/checkout
        with:
          lfs: false
      - name: Install rsync, gh, and curl üìö
        run: |
          apt-get update && apt-get install -y rsync gh curl
      - name: Setup üîß
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Setup rclone üîß
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Sync Assets üì•
        run: |
          cd ${PROJECT_PATH}
          mkdir assets
          rclone copy assets:assets ./assets
      - name: Web Build üõ†Ô∏è
        run: |
          mkdir -v -p build/web/
          cd $PROJECT_PATH
          godot -v --headless --export-debug "Web" ../build/web/index.html
      - name: Patch for Cross Origin Isolation and SharedArrayBuffer
        run: |
          cd build/web/
          curl https://raw.githubusercontent.com/josephrocca/clip-image-sorter/92b108dc670d0b56bd6b72963b0e86c4c862412e/enable-threads.js --output enable-threads.js
          sed -i 's|headers.set("Cross-Origin-Embedder-Policy", "credentialless")|headers.set("Cross-Origin-Embedder-Policy", "require-corp")|g'  enable-threads.js
          sed -i 's|<script src="index.js"></script>|<script src="enable-threads.js"></script><script src="index.js"></script>|g' index.html
      - name: Upload Artifact üì§
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
      - name: Deploy to GitHub Pages üöÄ
        uses: JamesIves/github-pages-deploy-action@releases/v4 # https://github.com/JamesIves/github-pages-deploy-action
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web/ # The folder the action should deploy.